sources:
- name: raw_draft_combine
  path: '''data/draft_combine.csv'''
- name: raw_draft
  path: '''data/draft.csv'''
- name: raw_game_inactive_players
  path: '''data/game_inactive_players.csv'''
- name: raw_game_inactive_players
  path: '''data/game_inactive_players.csv'''
- name: raw_game_officials
  path: '''data/game_officials.csv'''
- name: raw_game
  path: '''data/game.csv'''
- name: raw_News_Missing
  path: '''data/News_Missing.csv'''
- name: raw_news
  path: '''data/news.csv'''
- name: raw_player_attributes
  path: '''data/player_attributes.csv'''
- name: raw_player_bios
  path: '''data/player_bios.csv'''
- name: raw_player_photos
  path: '''data/player_photos.csv'''
- name: raw_player_salary
  path: '''data/player_salary.csv'''
- name: raw_player
  path: '''data/player.csv'''
- name: raw_team_attributes
  path: '''data/team_attributes.csv'''
- name: raw_team_history
  path: '''data/team_history.csv'''
- name: raw_team_salary
  path: '''data/team_salary.csv'''
- name: raw_team
  path: '''data/team.csv'''
models:
- name: stg_team_salary
  columns:
  - name: team_name
    tests:
    - type: not_null
    - type: unique
  - name: slug_team
  - name: 2020_salary
  - name: 2021_salary
  - name: 2022_salary
  - name: 2023_salary
  - name: 2024_salary
  - name: 2025_salary
