SELECT
    IDPLAYER AS ID_PLAYER,
    YEARCOMBINE AS YEAR_COMBINE,
    HEIGHTWOSHOESINCHES AS HEIGHT_WO_SHOES_INCHES,
    WINGSPANINCHES AS WINGSPAN_INCHES,
    SLUGPOSITION AS SLUG_POSITION
FROM
    q.raw_draft_combine
