SELECT
    IDPLAYER AS ID_PLAYER,
    YEARDRAFT AS YEAR_DRAFT,
    NUMBERPICKOVERALL AS NUMBER_PICK_OVERALL,
    NUMBERROUND AS NUMBER_ROUND,
    NUMBERROUNDPICK AS NUMBER_ROUND_PICK,
    NAMEPLAYER AS NAME_PLAYER,
    SLUGTEAM AS SLUG_TEAM,
    NAMEORGANIZATIONFROM AS NAME_ORGANIZATION_FROM,
    TYPEORGANIZATIONFROM AS TYPE_ORGANIZATION_FROM,
    IDTEAM AS ID_TEAM,
    NAMETEAM AS NAME_TEAM,
    CITYTEAM AS CITY_TEAM,
    TEAMNAME AS TEAM_NAME,
    PLAYER_PROFILE_FLAG,
    SLUGORGANIZATIONTYPEFROM AS SLUG_ORGANIZATION_TYPE_FROM,
    LOCATIONORGANIZATIONFROM AS LOCATION_ORGANIZATION_FROM
FROM
    q.raw_draft
