SELECT
    SLUGSEASON AS SLUG_SEASON,
    NAMETEAM AS TEAM_NAME,
    NAMEPLAYER AS PLAYER_NAME,
    STATUSPLAYER AS PLAYER_STATUS,
    ISFINALSEASON AS IS_FINAL_SEASON,
    ISWAIVED AS IS_WAIVED,
    ISONROSTER AS IS_ON_ROSTER,
    ISNONGUARANTEED AS IS_NON_GUARANTEED,
    ISTEAMOPTION AS IS_TEAM_OPTION,
    ISPLAYEROPTION AS IS_PLAYER_OPTION,
    TYPECONTRACTDETAIL AS TYPE_CONTRACT_DETAIL,
    VALUE
FROM
    q.raw_player_salary
